version: '3'
services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-custom
    ports:
      - 80:80
